services:
  - type: web
    name: dnse-intermediary-api
    env: docker
    plan: free # or starter
    region: singapore
    envVars:
      - key: DNSE_API_KEY
        sync: false
      - key: DNSE_API_SECRET
        sync: false
      - key: DNSE_BASE_URL
        value: "https://services.entrade.com.vn/dnse-market/v1"
